Đề:
https://docs.google.com/document/d/17-O0_W8IOwfIDH7Qhmmklyjae-LPK1KZ3DpjLfiPFTs/edit?usp=sharing

In [20]:
import numpy as np

Bài 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá  trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):

- np.arrange()  

- np.linspace() 

- np.logspace() 

- np.random.rand() 


In [21]:
""" numpy.arange(start, stop, step, dtype) """
a = np.arange(7)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[0 1 2 3 4 5 6]
số chiều: 1
kích thước: (7,)


In [22]:
""" numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0) """
a = np.linspace(1,10,num=7, dtype=int)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[ 1  2  4  5  7  8 10]
số chiều: 1
kích thước: (7,)


In [23]:
""" numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None, axis=0 ) """
a = np.logspace(1,3,num=7,base=3)
# kết quả trả về là 1 mãng chứa kết quả của base mũ lần lượt các số [start,end]/num
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[ 3.          4.32674871  6.24025147  9.         12.98024613 18.72075441
 27.        ]
số chiều: 1
kích thước: (7,)


In [24]:
""" random.rand(d0, d1, ..., dn) """
a = np.random.rand(7,1)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[[0.08746399]
 [0.27231769]
 [0.52311849]
 [0.85051415]
 [0.01719117]
 [0.22748364]
 [0.48103804]]
số chiều: 2
kích thước: (7, 1)


Bài 2

In [25]:
a = np.arange(70)
a.shape = (10,7)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
số chiều: 2
kích thước: (10, 7)


In [26]:
a = np.linspace(1,100,num=70, dtype=int).reshape(10,7)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[[  1   2   3   5   6   8   9]
 [ 11  12  13  15  16  18  19]
 [ 21  22  23  25  26  28  29]
 [ 31  32  34  35  36  38  39]
 [ 41  42  44  45  46  48  49]
 [ 51  52  54  55  56  58  59]
 [ 61  62  64  65  67  68  69]
 [ 71  72  74  75  77  78  79]
 [ 81  82  84  85  87  88  89]
 [ 91  92  94  95  97  98 100]]
số chiều: 2
kích thước: (10, 7)


In [27]:
a = np.logspace(1,70,num=70,base=2).reshape(10,7)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[[2.00000000e+00 4.00000000e+00 8.00000000e+00 1.60000000e+01
  3.20000000e+01 6.40000000e+01 1.28000000e+02]
 [2.56000000e+02 5.12000000e+02 1.02400000e+03 2.04800000e+03
  4.09600000e+03 8.19200000e+03 1.63840000e+04]
 [3.27680000e+04 6.55360000e+04 1.31072000e+05 2.62144000e+05
  5.24288000e+05 1.04857600e+06 2.09715200e+06]
 [4.19430400e+06 8.38860800e+06 1.67772160e+07 3.35544320e+07
  6.71088640e+07 1.34217728e+08 2.68435456e+08]
 [5.36870912e+08 1.07374182e+09 2.14748365e+09 4.29496730e+09
  8.58993459e+09 1.71798692e+10 3.43597384e+10]
 [6.87194767e+10 1.37438953e+11 2.74877907e+11 5.49755814e+11
  1.09951163e+12 2.19902326e+12 4.39804651e+12]
 [8.79609302e+12 1.75921860e+13 3.51843721e+13 7.03687442e+13
  1.40737488e+14 2.81474977e+14 5.62949953e+14]
 [1.12589991e+15 2.25179981e+15 4.50359963e+15 9.00719925e+15
  1.80143985e+16 3.60287970e+16 7.20575940e+16]
 [1.44115188e+17 2.88230376e+17 5.76460752e+17 1.15292150e+18
  2.30584301e+18 4.61168602e+18 9.22337204e+18]
 [1.844674

In [28]:
a = np.random.rand(10,7)
print(a)
print('số chiều:',np.ndim(a))
print("kích thước:",np.shape(a))

[[0.46310101 0.08267995 0.31895934 0.57728464 0.94324175 0.5235328
  0.19773549]
 [0.34980241 0.90362653 0.62539278 0.40011827 0.64047955 0.29599889
  0.59015979]
 [0.41323302 0.62335175 0.5289633  0.40092659 0.7934128  0.30251528
  0.33153447]
 [0.14890437 0.11459068 0.60686333 0.03753666 0.44499436 0.4402453
  0.6522694 ]
 [0.5176304  0.74700106 0.66934079 0.95537524 0.51038131 0.9851575
  0.27260151]
 [0.9285508  0.56620252 0.531435   0.27870432 0.32934395 0.42765073
  0.73871121]
 [0.73127138 0.32647633 0.1185194  0.14617383 0.62941685 0.9057657
  0.83080823]
 [0.78579202 0.7337443  0.59042022 0.66092636 0.77260693 0.39348618
  0.59255627]
 [0.17080989 0.0537516  0.10683341 0.33486219 0.29456344 0.62840666
  0.98272446]
 [0.72441069 0.44109179 0.94519789 0.24344057 0.4700114  0.50775671
  0.47233493]]
số chiều: 2
kích thước: (10, 7)


Bài 3

In [29]:
""" numpy_array.flatten(order) - order = {"C", "F"}"""
a = np.linspace(1,100,num=70, dtype=int).reshape(10,7)
print("Ma trận ban đầu:\n",a)
print("Làm phẳng ma trận:\n",a.flatten("C"))
print("Chuyển lại thành ma trận 10x7:\n",a.reshape(10,7))

Ma trận ban đầu:
 [[  1   2   3   5   6   8   9]
 [ 11  12  13  15  16  18  19]
 [ 21  22  23  25  26  28  29]
 [ 31  32  34  35  36  38  39]
 [ 41  42  44  45  46  48  49]
 [ 51  52  54  55  56  58  59]
 [ 61  62  64  65  67  68  69]
 [ 71  72  74  75  77  78  79]
 [ 81  82  84  85  87  88  89]
 [ 91  92  94  95  97  98 100]]
Làm phẳng ma trận:
 [  1   2   3   5   6   8   9  11  12  13  15  16  18  19  21  22  23  25
  26  28  29  31  32  34  35  36  38  39  41  42  44  45  46  48  49  51
  52  54  55  56  58  59  61  62  64  65  67  68  69  71  72  74  75  77
  78  79  81  82  84  85  87  88  89  91  92  94  95  97  98 100]
Chuyển lại thành ma trận 10x7:
 [[  1   2   3   5   6   8   9]
 [ 11  12  13  15  16  18  19]
 [ 21  22  23  25  26  28  29]
 [ 31  32  34  35  36  38  39]
 [ 41  42  44  45  46  48  49]
 [ 51  52  54  55  56  58  59]
 [ 61  62  64  65  67  68  69]
 [ 71  72  74  75  77  78  79]
 [ 81  82  84  85  87  88  89]
 [ 91  92  94  95  97  98 100]]


Bài 4

In [30]:
a = np.logspace(1,20,num=150,base=2).reshape(10,15)
print(a)

[[2.00000000e+00 2.18482356e+00 2.38672700e+00 2.60728869e+00
  2.84823289e+00 3.11144316e+00 3.39897717e+00 3.71308270e+00
  4.05621529e+00 4.43105737e+00 4.84053928e+00 5.28786214e+00
  5.77652290e+00 6.31034167e+00 6.89349158e+00]
 [7.53053142e+00 8.22644125e+00 8.98666134e+00 9.81713472e+00
  1.07243536e+01 1.17154103e+01 1.27980522e+01 1.39807430e+01
  1.52727284e+01 1.66841084e+01 1.82259166e+01 1.99102060e+01
  2.17501436e+01 2.37601131e+01 2.59558275e+01]
 [2.83544517e+01 3.09747371e+01 3.38371678e+01 3.69641207e+01
  4.03800410e+01 4.41116325e+01 4.81880671e+01 5.26412122e+01
  5.75058804e+01 6.28201012e+01 6.86254187e+01 7.49672159e+01
  8.18950699e+01 8.94631392e+01 9.77305872e+01]
 [1.06762045e+02 1.16628116e+02 1.27405928e+02 1.39179736e+02
  1.52041584e+02 1.66092017e+02 1.81440877e+02 1.98208151e+02
  2.16524920e+02 2.36534373e+02 2.58392936e+02 2.82271487e+02
  3.08356698e+02 3.36852490e+02 3.67981629e+02]
 [4.01987467e+02 4.39135845e+02 4.79717170e+02 5.24048689e+02
  

In [31]:
# Trích xuất hàng thứ 3
row3 = a[[3],:]
row3

array([[106.76204489, 116.62811565, 127.40592759, 139.17973633,
        152.0415837 , 166.09201731, 181.44087652, 198.20815115,
        216.52491951, 236.53437305, 258.39293585, 282.27148737,
        308.35669838, 336.85249021, 367.98162892]])

In [32]:
# Trích xuất cột thứ 5
col5 = a[:,[5]]
col5

array([[3.11144316e+00],
       [1.17154103e+01],
       [4.41116325e+01],
       [1.66092017e+02],
       [6.25380578e+02],
       [2.35472404e+03],
       [8.86616170e+03],
       [3.33834546e+04],
       [1.25697577e+05],
       [4.73284777e+05]])

Bài 5

In [39]:
from scipy import stats
def gia_tri_trung_binh(matrix,axis):
    return np.apply_along_axis(np.mean,axis,matrix)
def gia_tri_trung_vi(matrix,axis):
    return np.apply_along_axis(np.median,axis,matrix)
def gia_tri_yeu_vi(matrix,axis):
    return np.apply_along_axis(stats.mode,axis,matrix)
def phuong_sai(matrix,axis):
    return np.apply_along_axis(np.var,axis,matrix)
def do_lech_chuan(matrix,axis):
    return np.apply_along_axis(np.std,axis,matrix)

In [34]:
a = np.arange(150).reshape(15,10)
print(a)

[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]


In [43]:
# Áp dụng vào từng hàng
print("Giá trị trung bình: ", gia_tri_trung_binh(a,1))
print("Giá trị trung vị: ", gia_tri_trung_binh(a,1))
print("Giá trị yếu vị: ", gia_tri_yeu_vi(a,1).flatten())
print("Phương sai: ", phuong_sai(a,1))
print("Độ lệch chuẩn: ", do_lech_chuan(a,1))

Giá trị trung bình:  [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]
Giá trị trung vị:  [  4.5  14.5  24.5  34.5  44.5  54.5  64.5  74.5  84.5  94.5 104.5 114.5
 124.5 134.5 144.5]
Giá trị yếu vị:  [  0   1  10   1  20   1  30   1  40   1  50   1  60   1  70   1  80   1
  90   1 100   1 110   1 120   1 130   1 140   1]
Phương sai:  [8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25 8.25
 8.25]
Độ lệch chuẩn:  [2.87228132 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132
 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132 2.87228132
 2.87228132 2.87228132 2.87228132]


In [44]:
# Áp dụng vào từng cột
print("Giá trị trung bình: ", gia_tri_trung_binh(a,0))
print("Giá trị trung vị: ", gia_tri_trung_binh(a,0))
print("Giá trị yếu vị: ", gia_tri_yeu_vi(a,0).flatten())
print("Phương sai: ", phuong_sai(a,0))
print("Độ lệch chuẩn: ", do_lech_chuan(a,0))

Giá trị trung bình:  [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
Giá trị trung vị:  [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
Giá trị yếu vị:  [0 1 2 3 4 5 6 7 8 9 1 1 1 1 1 1 1 1 1 1]
Phương sai:  [1866.66666667 1866.66666667 1866.66666667 1866.66666667 1866.66666667
 1866.66666667 1866.66666667 1866.66666667 1866.66666667 1866.66666667]
Độ lệch chuẩn:  [43.20493799 43.20493799 43.20493799 43.20493799 43.20493799 43.20493799
 43.20493799 43.20493799 43.20493799 43.20493799]
