Đề: https://drive.google.com/file/d/1kayrhGpNiCAEeJQuDRtr1xF4re5xcvtT/view?usp=sharing

In [1]:
import numpy as np

Bài 1

In [2]:
a = np.array([5,7,14])
a

array([ 5,  7, 14])

Bài 2

In [5]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Bài 3

In [17]:
#n = int(input("Nhập n: "))
n = 10
a = np.random.randint(1,10,(1,n))
print('Vector OA = ',a)

Vector OA =  [[6 5 5 8 8 1 8 1 8 5]]


Bài 4

In [32]:
a = np.array([[7], [-5], [8]])
print('Vector OA = ',a)
print("Độ dài vector OA = ",(np.sum(a**2))**0.5)

Vector OA =  [[ 7]
 [-5]
 [ 8]]
Độ dài vector OA =  11.74734012447073


Bài 5 + 6 +7

In [42]:
#n = int(input("Nhập n: "))
n = 3
a = np.random.randint(1,10,(1,n))
print("Tọa độ điểm A",a)
b = np.random.randint(1,10,(1,n))
print("Tọa độ điểm B",b)
ab = b-a
print("Vector AB =",ab)
print("Độ dài vector AB = ",(np.sum(ab**2))**0.5)
print("Tích vô hướng =",np.inner(a,b))
print("Tích hữu hướng =",np.cross(a,b))

Tọa độ điểm A [[4 1 4]]
Tọa độ điểm B [[3 8 8]]
Vector AB = [[-1  7  4]]
Độ dài vector AB =  8.12403840463596
Tích vô hướng = [[52]]
Tích hữu hướng = [[-24 -20  29]]


Bài 8

In [44]:
#n = int(input("Nhập n: "))
n = 3
a = np.random.randint(1,10,(1,n))
print("Vector A:",a)
aT = np.transpose(a)
print("Vector A chuyển vị:\n",aT)


Vector A: [[9 7 3]]
Vector A chuyển vị:
 [[9]
 [7]
 [3]]


Bài 9

In [58]:
a = [1, 2, 3, 4, 5]
b = np.array([[1], [2], [3], [4], [5]])
print(f'-- Ban đầu --\na:\n{a}\nb:\n{b}')
# Chuyển a và b thành vector
a = np.array(a).reshape(1,5)
b = b.reshape(5,1)
print(f'-- Chuyển thành vector --\na:\n{a}\nb:\n{b}')
# Chuyển vị vector a và b
aT = np.transpose(a)
bT = np.transpose(b)
print(f'-- Chuyển vị vector --\na:\n{aT}\nb:\n{bT}')

-- Ban đầu --
a:
[1, 2, 3, 4, 5]
b:
[[1]
 [2]
 [3]
 [4]
 [5]]
-- Chuyển thành vector --
a:
[[1 2 3 4 5]]
b:
[[1]
 [2]
 [3]
 [4]
 [5]]
-- Chuyển vị vector --
a:
[[1]
 [2]
 [3]
 [4]
 [5]]
b:
[[1 2 3 4 5]]


Bài 10

In [61]:
#n = int(input("Nhập n: "))
n = 3
a = np.random.randint(1,10,(1,n))
print("Vector A:",a)
b = np.random.randint(1,10,(1,n))
print("Vector B:",b)

m=5
print("Phép nhân: m.a =",m*a)
print("Phép cộng: a+b =",a+b)

Vector A: [[5 3 7]]
Vector B: [[3 8 2]]
Phép nhân: m.a = [[25 15 35]]
Phép cộng: a+b = [[ 8 11  9]]
