In [1]:
import numpy as np

Bài 1

In [6]:
a = np.random.randint(1,10,(7,5))
print(a)

[[4 5 6 3 9]
 [3 2 1 2 1]
 [7 9 7 4 2]
 [4 5 4 8 9]
 [1 2 5 1 1]
 [5 8 7 1 2]
 [8 3 5 2 4]]


Bài 2

In [11]:
a = np.zeros(shape=(6,7))
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3

In [12]:
a = np.random.randint(1,10,(7,7))
print(a)

[[3 2 5 5 8 3 1]
 [4 1 9 3 4 3 8]
 [5 5 5 3 2 4 1]
 [7 9 8 8 2 9 8]
 [1 3 2 2 3 1 4]
 [6 1 1 6 4 8 8]
 [2 4 5 8 4 7 1]]


Bài 4

In [15]:
a = np.zeros(shape=(6,6))
np.fill_diagonal(a,15)
print(a)

[[15.  0.  0.  0.  0.  0.]
 [ 0. 15.  0.  0.  0.  0.]
 [ 0.  0. 15.  0.  0.  0.]
 [ 0.  0.  0. 15.  0.  0.]
 [ 0.  0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0.  0. 15.]]


Bài 5 + 6

In [22]:
a = np.random.randint(1,10,(6,6))
print("Ma trận tam giác trên:\n",np.triu(a))
print("Ma trận tam giác dưới:\n",np.transpose(np.triu(a)))

Ma trận tam giác trên:
 [[8 5 1 9 9 6]
 [0 1 3 9 4 2]
 [0 0 2 7 8 3]
 [0 0 0 7 8 6]
 [0 0 0 0 6 7]
 [0 0 0 0 0 9]]
Ma trận tam giác dưới:
 [[8 0 0 0 0 0]
 [5 1 0 0 0 0]
 [1 3 2 0 0 0]
 [9 9 7 7 0 0]
 [9 4 8 8 6 0]
 [6 2 3 6 7 9]]


Bài 7

In [24]:
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Bài 8

In [28]:
a = np.random.randint(1,10,(6,7))
b = np.random.randint(1,10,(6,7))
print("Phép cộng ma trận:\n",a+b)

Phép cộng ma trận:
 [[16 11 11  3 11 11  6]
 [11  9 15  6 12 10 15]
 [11  4 11 11 14 12  5]
 [ 9  9 11 12 17 11 12]
 [ 5  6 12 13  9 10 17]
 [ 8  6 10 11 10 10  7]]


In [30]:
a = np.random.randint(1,10,(6,7))
print("Tích vô hướng ma trận với 1 số:\n",np.inner(a,5))

Tích vô hướng ma trận với 1 số:
 [[30 40 25  5 45 45 20]
 [25 45 15 20 10 25 15]
 [35 35 30 40 10  5 25]
 [35 35 30 25  5  5 30]
 [ 5 30 15  5 15 10 40]
 [20 25 10 35 25 20 45]]


In [35]:
a = np.random.randint(1,10,(3,7))
print("Vector chuyển vị:\n",np.transpose(a))

Vector chuyển vị:
 [[9 6 8]
 [2 7 5]
 [5 5 2]
 [6 4 6]
 [5 5 7]
 [7 3 2]
 [1 1 6]]


In [34]:
a = np.random.randint(1,10,(5,7))
b = np.random.randint(1,10,(7,5))
print("Phép nhân 2 ma trận:\n",np.dot(a,b))

Phép nhân 2 ma trận:
 [[132 117 161 123 158]
 [201 161 165 183 187]
 [144 145 131 149 151]
 [155 139 180 161 152]
 [169 174 150 176 182]]


In [39]:
a = np.random.randint(1,10,(5,7))
print("Vector khả nghịch:\n",np.linalg.pinv(a))

Vector khả nghịch:
 [[-0.08910203  0.12437498  0.10404749 -0.05309319 -0.02429229]
 [-0.08426123  0.01066862  0.13479766 -0.01676482  0.01100933]
 [-0.25401091  0.01468359  0.07184551 -0.0512922   0.23159529]
 [-0.36815286 -0.01872685  0.10818771  0.03858399  0.26872997]
 [ 0.18651584 -0.11440966 -0.05625063  0.01329995 -0.01925558]
 [ 0.18301069  0.09092022 -0.11432308  0.11248805 -0.23892794]
 [ 0.329816    0.01474017 -0.16231662  0.04317901 -0.21022714]]


Bài 9

In [40]:
a = np.random.randint(1,10,(1,8))
print("Row vector:\n",a)
a = np.random.randint(1,10,(8,1))
print("Row vector:\n",a)

Row vector:
 [[6 5 9 8 1 3 3 7]]
Row vector:
 [[8]
 [5]
 [2]
 [3]
 [6]
 [8]
 [7]
 [4]]


Bài 10

![image](https://user-images.githubusercontent.com/70121634/157868695-2ee29720-c077-47ce-81cb-5aef1e394e30.png)

In [52]:
m = 4
n = 5
a = np.random.randint(-10,10,(m,n))
print("Vector A:\n",a)
b = np.random.randint(-10,10,(m,1))
print("Vector B:\n",b)
x = np.dot(np.linalg.pinv(a),b)
print("=> Vector X:\n",x)

Vector A:
 [[ -3   7   4   6   6]
 [ -6  -3   7   3   2]
 [  1   9  -2   8   4]
 [ -4  -7  -4   8 -10]]
Vector B:
 [[ 7]
 [-3]
 [-1]
 [-7]]
=> Vector X:
 [[-4.09809514]
 [ 4.4838347 ]
 [ 0.18886229]
 [-2.98024357]
 [-3.25918601]]
