Đề: https://drive.google.com/file/d/1H59t1UIuNTS70JtuT7H8dyDdN_Ro9MC-/view?usp=sharing

In [25]:
import numpy as np

**Syntax:**

![image](https://user-images.githubusercontent.com/70121634/157898649-3d6676e0-ae7c-490f-95e6-cfe1f037cb2c.png)

*1d_func* -- Nhập hàm muốn thực hiện trên các mảng 1D được trích xuất từ mảng ban đầu

*axis* -- 0 nếu muốn cắt mảng ban đầu theo cột / 1 nếu muốn cắt mảng ban đầu theo hàng

*array* -- Nhập mảng muốn thực hiện

Bài 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [26]:
a = np.random.randint(10,100,(15,17))
print(a)

[[15 21 16 61 48 75 23 29 47 17 79 90 91 30 44 17 81]
 [32 42 43 44 79 12 26 43 46 77 58 86 83 16 49 33 28]
 [86 48 63 56 27 67 73 14 68 91 41 96 28 40 10 26 89]
 [39 69 34 83 90 33 39 11 59 11 54 20 52 26 17 80 73]
 [49 67 24 21 48 48 49 81 72 13 46 17 27 30 38 50 29]
 [73 56 22 72 89 23 34 85 68 23 62 92 86 22 72 88 98]
 [87 70 96 46 13 97 72 41 81 12 25 47 18 92 31 83 83]
 [48 22 32 13 24 19 24 80 72 79 13 32 30 75 62 10 53]
 [50 10 38 59 47 69 51 39 76 31 47 87 99 38 17 83 75]
 [70 29 72 22 45 91 44 32 49 32 17 69 20 29 84 20 72]
 [48 82 93 98 38 40 19 81 50 34 47 52 43 87 94 38 86]
 [11 18 44 20 41 76 56 33 90 67 78 75 39 28 70 30 42]
 [94 38 45 19 87 63 17 43 80 94 16 10 35 88 96 76 93]
 [46 46 97 97 31 89 23 20 76 73 71 52 11 73 76 34 81]
 [54 43 36 54 90 16 12 77 81 85 55 16 60 45 78 61 76]]


Bài 3

In [27]:
def tim_gia_tri_lon_nhat(vector):
    return np.apply_along_axis(np.max, 1, vector)
print(tim_gia_tri_lon_nhat(a))

[91 86 96 90 81 98 97 80 99 91 98 90 96 97 90]


Bài 4

In [28]:
def tim_gia_tri_nho_nhat(vector):
    return np.apply_along_axis(np.min, 0, vector)
print(tim_gia_tri_nho_nhat(a))

[11 10 16 13 13 12 12 11 46 11 13 10 11 16 10 10 28]


Bài 5

In [29]:
def tinh_tong(vector):
    return np.apply_along_axis(np.sum, 0, vector)
print(tinh_tong(a))

[ 802  661  755  765  797  818  562  709 1015  739  709  841  722  719
  838  729 1059]


Bài 6

In [30]:
b = np.random.randint(1,10,(2,4))
print(b)

[[6 9 8 8]
 [6 1 2 2]]


In [31]:
def tinh_tong_2(vector,axis):
    for x in range(len(vector)):
        for
    return np.apply_along_axis(np.sum, axis, vector)
print(tinh_tong_2(a,0))

TypeError: only integer scalar arrays can be converted to a scalar index