# Numpy

### Thêm thư viện

Cài đặt thư viện

*pip install numpy*

In [57]:
import numpy as np

### Khởi tạo mảng

In [58]:
""" Mảng 1 chiều """
arr1 = np.array([1,3,4,5,6])
arr1

array([1, 3, 4, 5, 6])

In [59]:
""" Mảng 2 chiều """
arr2 = np.array(((2,4,0,6), (4,7,5,6),
                 (0,3,2,1), (9,4,5,6)))
arr2

array([[2, 4, 0, 6],
       [4, 7, 5, 6],
       [0, 3, 2, 1],
       [9, 4, 5, 6]])

dtype: Kiểu dữ liệu của phần tử trong mảng

shape: Kích thước của mảng

size: Số phần tử trong mảng

ndim: Số chiều của mảng

In [67]:
print("Kiểu dữ liệu của phần tử trong mảng:", arr2.dtype)
print("Kích thước của mảng:", arr2.shape)
print("Số phần tử trong mảng:", arr2.size)
print("Số chiều của mảng:", arr2.ndim)

Kiểu dữ liệu của phần tử trong mảng: int32
Kích thước của mảng: (4, 4)
Số phần tử trong mảng: 16
Số chiều của mảng: 2


In [60]:
""" Tạo mảng hai chiều các phần tử 0 với kích thước 3×4 """
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [61]:
""" Tạo mảng 3 chiều các phần tử 1 với kích thước 2x3x4 """
np.ones((2,3,4), dtype = int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [62]:
""" Tạo mảng với các phần tử từ 1 đến 25 với bước nhảy là 2 """
np.arange(1,26,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [63]:
""" Tạo mảng 2 chiều các phần tử 5 với kích thước 2×3 """
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [64]:
""" Tạo ma trận đơn vị với kích thước là 4×4 """
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [65]:
""" Tạo ma trận các phần tử ngẫu nhiên với kích thước 2×3 """
np.random.random((2,3))

array([[0.06006147, 0.89514907, 0.44569397],
       [0.33398261, 0.0271108 , 0.77892902]])

In [66]:
""" Tạo ma trận các phần tử ngẫu nhiên từ 1 đến 99 với kích thước 3x3 """
np.random.randint(1,100,(3,3))

array([[76, 96, 65],
       [50, 51,  7],
       [78, 58, 81]])

### Các hàm thống kê



arr.max() hoặc np.max(arr): Lấy giá trị lớn nhất của mảng arr

arr.min() hoặc np.min(arr): Lấy giá trị nhỏ nhất của mảng arr

arr.sum() hoặc np.sum(arr): Tổng tất cả các phần tử trong mảng arr

arr.mean() hoặc np.mean(arr): Trung bình cộng của tất cả các phần tử trong mảng arr

np.median(arr): Trả về giá trị trung vị của mảng arr

In [68]:
print(arr)
print("Giá trị lớn nhất của mảng arr là:", np.max(arr))
print("Giá trị nhỏ nhất của mảng arr là:", np.min(arr))
print("Tổng tất cả các phần tử của mảng arr là:", np.sum(arr))
print("Trung bình cộng tất cả các phần tử của mảng arr là:", np.mean(arr))
print("Giá trị trung vị của mảng arr là:", np.median(arr))

[1 3 4 5 6]
Giá trị lớn nhất của mảng arr là: 6
Giá trị nhỏ nhất của mảng arr là: 1
Tổng tất cả các phần tử của mảng arr là: 19
Trung bình cộng tất cả các phần tử của mảng arr là: 3.8
Giá trị trung vị của mảng arr là: 4.0


### Toán tử

In [69]:
a = np.array(([2,1],[9,5]))
b = np.array(([11,42],[75,36]))

In [70]:
""" Cộng/trừ 1 số với ma trận """
a + 3

array([[ 5,  4],
       [12,  8]])

In [71]:
""" Ma trận cộng/trừ ma trận """
a + b

array([[13, 43],
       [84, 41]])

In [72]:
""" Nhân/chia 1 số với mảng """
a * 5

array([[10,  5],
       [45, 25]])

In [73]:
""" Ma trận nhân ma trận """
np.dot(a,b)

array([[ 97, 120],
       [474, 558]])

### Identify matrix và Transpose matrix

In [79]:
a

array([[2, 1],
       [9, 5]])

In [74]:
""" Identify matrix - Ma trận khả nghịch (arr^-1) """
np.linalg.pinv(a)

array([[ 5., -1.],
       [-9.,  2.]])

In [75]:
""" Transpose matrix - Ma trận chuyển vị (arrT) """
np.transpose(a)

array([[2, 9],
       [1, 5]])